### ISSUE TITLE
Cloned repo uses a more updated reference than the one it needs, it does not build

### ISSUE THREAD

**Issue by gzepeda** [Microsoft/ApplicationInsights-aspnetcore#138]
I cloned the repository today and noticed some errors on the package restoring:
```
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary2.set_Item(TKey key, TValue value)
   at Microsoft.NodejsTools.Npm.SPI.AbstractNodeModules.AddModule(IPackage package)
   at Microsoft.NodejsTools.Npm.SPI.NodeModules..ctor(IRootPackage parent, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.RootPackage..ctor(String fullPathToRootDirectory, Boolean showMissingDevOptionalSubPackages)
   at Microsoft.NodejsTools.Npm.SPI.NpmController.<RefreshAsync>d__1.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
```

After that I went ahead and built the project and got the following error

![2016-03-02 15_36_09-applicationinsights aspnet - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/4001077/13479806/2b6805b4-e09f-11e5-8a18-7f9ef26a693f.png)

The workaround suggested by @SergeyKanzhelev is to change a reference on the project.json file of the source code of the project:
 
`"Microsoft.ApplicationInsights": "2.0.0-beta4",`
 
Instead of:
 
`"Microsoft.ApplicationInsights": "2.0.0-*",`

I have tested it and it builds successfully.

**Comment by SergeyKanzhelev** [comment]
Fixed compilation issues - pull from develop branch. Need to look closer on npm warning.

**Comment by gzepeda** [comment]
Great! thanks!
