### ISSUE TITLE
asp.net core 1.1 and appinsights.core 1.0.2

### ISSUE THREAD

**Issue by cherici-simone** [Microsoft/ApplicationInsights-aspnetcore#301]
Hello, I've upgrade my 1.0 asp.net core web app (net461 framework) to 1.1 and I have a lot of problem with "UseApplicationInsightsRequestTelemetry()".
First of all I have to move UseApplicationInsightsRequestTelemetry() as the last row of my Configure(...) method (because using it before make my web app not working!) then (in output console) I see many of this error:

```
Exception: System.MissingMethodException: Method not found: 'Void Microsoft.ApplicationInsights.DataContracts.ISupportSampling.set_SamplingPercentage(Double)'.
   at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.SamplingTelemetryProcessor.Process(ITelemetry item)
   at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor.Process(ITelemetry item)
   at Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryProcessor.Process(ITelemetry telemetry)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Process(ITelemetry item)
   at Microsoft.ApplicationInsights.TelemetryClient.Track(ITelemetry telemetry)
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.ClientServerDependencyTracker.EndTracking(TelemetryClient telemetryClient, DependencyTelemetry telemetry)
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.FrameworkHttpProcessing.OnEndHttpCallback(Int64 id, Nullable`1 success, Boolean synchronous, Nullable`1 statusCode)
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.FrameworkHttpEventListener.OnEndGetResponse(EventWrittenEventArgs eventData)
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.FrameworkHttpEventListener.OnEventWritten(EventWrittenEventArgs eventData)
```

Any help?

**Comment by cherici-simone** [comment]
Oh...any idea on the delivery date of v 2.0?
Or, any workaround available? 
Our web app will be soon in production and I would like to have all possible telemetry.
Thank you

**Comment by alan-araya** [comment]
I´am having the same inssue. Can´t determine what happend exactally, but we were using normally the version 1.02 and that error start happening.

**My stack trace:**

Exception thrown: 'System.NullReferenceException' in PrbUtil.dll
Exception thrown: 'System.MissingMethodException' in Microsoft.AI.PerfCounterCollector.dll
Callback 'FrameworkSqlEventListener.OnEventWritten' failed for id = '0'. Exception: System.MissingMethodException: Method not found: 'Void Microsoft.ApplicationInsights.DataContracts.ISupportSampling.set_SamplingPercentage(Double)'.
   at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.SamplingTelemetryProcessor.Process(ITelemetry item)
   at Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryProcessor.Process(ITelemetry telemetry)
   at Microsoft.ApplicationInsights.TelemetryClient.Track(ITelemetry telemetry)
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.FrameworkSqlProcessing.OnEndExecuteCallback(Int64 id, Boolean success, Boolean synchronous, Int32 sqlExceptionNumber)
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.FrameworkSqlEventListener.OnEndExecute(EventWrittenEventArgs eventData)
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.FrameworkSqlEventListener.OnEventWritten(EventWrittenEventArgs eventData)

**Comment by dnduffy** [comment]
@alan-araya Did you upgrade your .NET Core CLI to 1.1?
Please try the new [2.0.0-beta1](https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.0.0-beta1) package.

**Comment by cherici-simone** [comment]
I've update to  2.0.0-beta1 package and seems to work as expected.
Thanks

**Comment by alan-araya** [comment]
@dnduffy Yes I´am running on CLI 1.1
Updated to 2.0.0-beta1 package and worked here too.
Just to clarify, what happens with these two entries on Startup class?

```
 app.UseApplicationInsightsRequestTelemetry();
 app.UseApplicationInsightsExceptionTelemetry();
```

They are marked with Obsolete tag, but there's no instruction about the new method that replaced it.
Also, is there a rodmap of the final version of 2.0 to be released?

Thanks

**Comment by dnduffy** [comment]
The first entry you definitely do not need anymore.
The second one is debatable, as I currently understand it, if you want an exception tracking middleware then you can still use it otherwise the framework will automatically only track for exceptions that are not suppressed by some other middleware.

**Comment by epot** [comment]
Is there a fix that does not make us migrate to a beta version of .net core ?

**Comment by dnduffy** [comment]
Neither .NET Core 1.0.1 or 1.1 is beta, the AI SDK 2.0.0-beta1 is beta but that is independent of .NET Core.

**Comment by epot** [comment]
My bad, I misunderstood the fix ! Thanks !
