### ISSUE TITLE
Exception while initializing Microsoft.ApplicationInsights.AspNetCore.ContextInitializers.DomainNameRoleInstanceTelemetryInitializer, exception message - System.ArgumentNullException: Value cannot be null.  Parameter name: provider

### ISSUE THREAD

**Issue by dnduffy** [Microsoft/ApplicationInsights-aspnetcore#363]
AI (Internal): [msg=Log Error];[msg=Exception while initializing Microsoft.ApplicationInsights.AspNetCore.ContextInitializers.DomainNameRoleInstanceTelemetryInitializer, exception message - System.ArgumentNullException: Value cannot be null.
Parameter name: provider
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.TelemetryInitializerBase.Initialize(ITelemetry telemetry)
   at Microsoft.ApplicationInsights.TelemetryClient.Initialize(ITelemetry telemetry)]

**Comment by dnduffy** [comment]
The exact same exception also occurs in the Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.ClientIpHeaderTelemetryInitializer.

**Comment by scottb1978** [comment]
Should this code for bot service work?
https://github.com/christopheranderson/azure-functions-app-insights-sample/tree/master/cs-http

I'm getting this error with the TrackEvent

**Comment by galvesribeiro** [comment]
Any updates on this? I'm still having the same issue today with Azure functions and AI...
