### ISSUE TITLE
Exception while initializing Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebSessionTelemetryInitializer, exception message - System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by dnduffy** [microsoft/ApplicationInsights-aspnetcore#364]
AI (Internal): [msg=Log Error];[msg=Exception while initializing Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebSessionTelemetryInitializer, exception message - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest.get_Cookies()
   at Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebSessionTelemetryInitializer.UpdateRequestTelemetryFromPlatformContext(RequestTelemetry requestTelemetry, HttpContext platformContext)
   at Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebSessionTelemetryInitializer.OnInitializeTelemetry(HttpContext platformContext, RequestTelemetry requestTelemetry, ITelemetry telemetry)
   at Microsoft.ApplicationInsights.TelemetryClient.Initialize(ITelemetry telemetry)]

**Comment by davenewza** [comment]
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/512

**Comment by cijothomas** [comment]
closing in favor of newly opened issue. https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/903
