### ISSUE TITLE
Capturing Startup exceptions

### ISSUE THREAD

**Issue by andrasg** [microsoft/ApplicationInsights-aspnetcore#392]
Hello,

Not really an issue, but rather a question: is there a way to capture exceptions that happen in the Startup method and prevent the application from starting? I don't see telemetry for these exceptions.

```
Application startup exception: System.ArgumentNullException: Value cannot be null.
Parameter name: String
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at MyApplication.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IServiceProvider serviceProvider, IOptionsMonitor`1 operationConfig, IOptionsMonitor`1 backendConfig, IOptionsMonitor`1 appInsightsOptions, TelemetryClient tc, ILogger`1 logger, IShardManagementService shardManagementService) in C:\agent\_work\1\s\src\MyApplication\Startup.cs:line 247
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.ArgumentNullException: Value cannot be null.
Parameter name: String
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at MyApplication.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IServiceProvider serviceProvider, IOptionsMonitor`1 operationConfig, IOptionsMonitor`1 backendConfig, IOptionsMonitor`1 appInsightsOptions, TelemetryClient tc, ILogger`1 logger, IShardManagementService shardManagementService) in C:\agent\_work\1\s\src\MyApplication\Startup.cs:line 247
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

**Comment by cijothomas** [comment]
Will need to make a doc/wiki about how to use AI TelemetryClient to atleast manually track Exceptions in those cases.

**Comment by cijothomas** [comment]
SDK now support capturing ILogger traces from startup.cs itself, so any exception occuring in this stage, can be logged via ILogger (passing in exception object if needed), and SDK is expected to capture that. The caveat is - if the app dies before the event is dispatched by SDK to backed, then telemetry won't be captured.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#capturing-ilogger-logs-from-startupcs-programcs-in-aspnet-core-applications

**Comment by cijothomas** [comment]
Closing this as new Ilogger exceptions can somewhat solve this.
