### ISSUE TITLE
RequestTrackingMiddlewareTests are still unstable and cause unit test builds to fail.

### ISSUE THREAD

**Issue by dnduffy** [Microsoft/ApplicationInsights-aspnetcore#412]
xUnit.net .NET CLI test runner (64-bit Desktop .NET win81-x64)
    Discovering: Microsoft.ApplicationInsights.AspNetCore.Tests
    Discovered:  Microsoft.ApplicationInsights.AspNetCore.Tests
    Starting:    Microsoft.ApplicationInsights.AspNetCore.Tests
      Microsoft.ApplicationInsights.AspNetCore.Tests.RequestTrackingMiddlewareTest.TestRequestUriIsPopulatedByMiddleware [FAIL]
        System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
        Stack Trace:
             at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
          RequestTrackingMiddlewareTest.cs(122,0): at Microsoft.ApplicationInsights.AspNetCore.Tests.RequestTrackingMiddlewareTest.TestRequestUriIsPopulatedByMiddleware()
      Microsoft.ApplicationInsights.AspNetCore.Tests.RequestTrackingMiddlewareTest.RequestWillBeMarkedAsFailedForRunawayException [FAIL]
        System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
        Stack Trace:
             at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
          RequestTrackingMiddlewareTest.cs(150,0): at Microsoft.ApplicationInsights.AspNetCore.Tests.RequestTrackingMiddlewareTest.RequestWillBeMarkedAsFailedForRunawayException()
      Microsoft.ApplicationInsights.AspNetCore.Tests.RequestTrackingMiddlewareTest.TestSdkVersionIsPopulatedByMiddleware [FAIL]
        System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
        Stack Trace:
             at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
          RequestTrackingMiddlewareTest.cs(96,0): at Microsoft.ApplicationInsights.AspNetCore.Tests.RequestTrackingMiddlewareTest.TestSdkVersionIsPopulatedByMiddleware()

**Comment by dnduffy** [comment]
https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/479

**Comment by dnduffy** [comment]
https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/481
