### ISSUE TITLE
Need to clean up obsolete method usage warnings.

### ISSUE THREAD

**Issue by dnduffy** [Microsoft/ApplicationInsights-aspnetcore#413]
e.g.: warning CS0618: 'RequestTelemetry.HttpMethod' is obsolete: 'Include http verb into request telemetry name and use custom properties to report http method as a dimension.'

**Comment by abatishchev** [comment]
Please document sample solution and provide a link to it in the message.

**Comment by cijothomas** [comment]
@abatishchev do you mean example AspNet Core Apps and how it uses ApplicationInsights? 
Will try to add a .net core sample here:
https://github.com/Microsoft/ApplicationInsights-Home/tree/master/Samples

**Comment by abatishchev** [comment]
@cijothomas I mean how to include http verb into request telemetry name and use custom properties to report http method as a dimension

**Comment by roberino** [comment]
I've also noticed that telemetryClient.StopOperation(operation) throws the exception below if the RequestTelemetry.HttpMethod property is not set (even though the property is marked obsolete).

`Newtonsoft.Json.JsonSerializationException occurred
  HResult=0x80131500
  Message=Error getting value from 'HttpMethod' on 'Microsoft.ApplicationInsights.DataContracts.RequestTelemetry'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at 
   at Microsoft.ApplicationInsights.TelemetryClient.Track(ITelemetry telemetry)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.OperationHolder`1.Dispose(Boolean disposing)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.OperationHolder`1.Dispose()`

**Comment by cijothomas** [comment]
Closing, as this was fixed with commit 71937799
