### ISSUE TITLE
'System.Diagnostics.HttpHandlerDiagnosticListener' threw an exception.

### ISSUE THREAD

**Issue by mehmetilker** [Microsoft/ApplicationInsights-aspnetcore#465]
Everything was working with following configuration:

On Azure App Service 
Asp.net Mvc Core (.Net Framework)
Microsoft.ApplicationInsights.AspNetCore 2.1.0-beta4

On App Service Extensions page (if I am not wrong) a notification advised me to install "ASP.NET Core Extensions" to be able to use "Azure logging".
I did and after that my web site stopped resulting with "HTTP Error 500.0 - Internal Server Error"

When I turned on stdoutLogEnabled setting I got following exception:

```
Application startup exception: System.TypeInitializationException: The type initializer for 'System.Diagnostics.HttpHandlerDiagnosticListener' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Diagnostics.DiagnosticListener..ctor(String name)
   at System.Diagnostics.HttpHandlerDiagnosticListener..ctor()
   at System.Diagnostics.HttpHandlerDiagnosticListener..cctor()
   --- End of inner exception stack trace ---
   at System.Diagnostics.DiagnosticListener.get_AllListeners()
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsInitializer.Start()
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass3_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Hosting environment: Production
Content root path: D:\home\site\wwwroot
```

I uninstalled "ASP.NET Core Extensions". No success.
I upgraded to Microsoft.ApplicationInsights.AspNetCore 2.1.0-beta5. No success.

After I removed the line UseApplicationInsights() from my Program.Main method, and publish again problem solved.

I assume that line should be there but going back with uninstalling "ASP.NET Core Extensions" does not work.
Is there anything else I can do ?

**Comment by mehmetilker** [comment]
It seems that problem was about as specified here:
https://github.com/Microsoft/ApplicationInsights-aspnetcore/releases/tag/v2.1.0-beta5
You should also include an explicit reference to System.Diagnostics.DiagnosticSource 4.4.0-preview2-25330-01 since it contains a critical bug fix this release relies on (you can remove this reference when 2.1.0 stable ships with an updated reference).

**Comment by dnduffy** [comment]
I'm glad you got it figured out, sorry for the difficulty.
