### ISSUE TITLE
TelemetryChannel for Linux

### ISSUE THREAD

**Issue by nburoojy** [Microsoft/ApplicationInsights-aspnetcore#551]
Hi,

Is this library supported in Linux environments?

I tried to run v 2.1.1 on Linux and got an exception about a missing ServerTelemetryChannel

I noticed this PR by @iusafaro and @cijothomas to enable ServerTelemetryChannel by default
https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/530

So I tried 2.2.0-beta1 and get an exception about the platform (probably that it's Linux)
```
Unhandled Exception: System.PlatformNotSupportedException: Windows Principal functionality is not supported on this platform.
   at System.Security.Principal.WindowsIdentity.GetCurrent()
   at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.Implementation.ApplicationFolderProvider..ctor(IDictionary environment, String folderName)
   at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.Implementation.Transmitter.Initialize()
   at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.ServerTelemetryChannel.Initialize(TelemetryConfiguration configuration)
   at Microsoft.Extensions.DependencyInjection.TelemetryConfigurationOptionsSetup.Configure(TelemetryConfiguration configuration)
   at Microsoft.Extensions.DependencyInjection.TelemetryConfigurationOptions..ctor(IEnumerable`1 configureOptions)
--- End of stack trace from previous location where exception was thrown ---
```

Thanks!

**Comment by cijothomas** [comment]
@nburoojy Thanks for reporting the isssue!
The exception stack you have pasted is arising from the recent change introduced in beta1.
Question - did you have trouble with it in 2.1.1?

**Comment by frohikey** [comment]
I got the same problem on OSX 10.12.6.

`2.2.0-beta1` - the same exception as @nburoojy posted
`2.1.1` - everything's ok

**Comment by cijothomas** [comment]
Thanks @frohikey for reporting the issue!
2.2.0-beta1 enables ServerTelemetryChannel, and this module uses local folder to store the telemetry data before sending to Application Insights Service. There is a code which was Windows-specific and causes the exception/application crash.

We are working to release the fix in beta2.

**Comment by nburoojy** [comment]
On `2.1.1` I get this exception
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AI.ServerTelemetryChannel, Version=2.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

   at Microsoft.Extensions.DependencyInjection.TelemetryConfigurationOptionsSetup.AddTelemetryChannelAndProcessors(TelemetryConfiguration configuration)
   at Microsoft.Extensions.DependencyInjection.TelemetryConfigurationOptionsSetup.Configure(TelemetryConfiguration configuration)
   at Microsoft.Extensions.DependencyInjection.TelemetryConfigurationOptions..ctor(IEnumerable`1 configureOptions)
```

**Comment by nburoojy** [comment]
Thanks @cijothomas

**Comment by cijothomas** [comment]
@nburoojy 2.1.1 does not support ServerTelemetryChannel. It only has InMemoryChannel. 2.2.0-beta1 is the first version which support ServerTelemetryChannel (and it appears broken in non-windows).
https://github.com/Microsoft/ApplicationInsights-aspnetcore/releases

**Comment by cijothomas** [comment]
Additional information:
ServerTelemetryChannel is compiled against NET Standard 1.3, and as of now there is .net API to set file permissions in non-windows. (https://github.com/dotnet/corefx/issues/15289)
So for non-windows, channel will not able to secure the temp folder where it stores telemetry (when network issues occur).
This means channel will continue to work normally, except that items will be dropped if there are network issues.
Even with the fix, persistent storage won't come automatically for non-windows customers. To make use of persistent storage, either create directory and give the directory location to ServerTelemetryChannel.StorageFolder, or set the flag ServerTelemetryChannel.AllowUnsecureLocalStorage to true.
